### ISSUE TITLE
Reduce complexity when parsing content

### ISSUE THREAD

**Issue by ccoVeille** [supitsdu/clipper#14]
The complexity of the code was increased with #13 by the multiple branching if 

The parsing of the content could be moved out the main with something like this

```go

contentStr, err := parseContent(flag)
if err != nil {
fmt.Println
os.Exitt(1)
}

// …

func parseContent(flag) string, error {
   if directText != {
      return *directText
   }

   // …
}
```

_Originally posted by @ccoVeille in https://github.com/supitsdu/clipper/pull/13#discussion_r1649901636_

**Comment by karimalzalek** [comment]
@supitsdu hello there, working on my first issue. I'v forked the repo and will give this a try.

**Comment by ccoVeille** [comment]
I would like you to reopen the issue, because my code reviews was missed (by my fault)

Please have a look here
https://github.com/supitsdu/clipper/pull/15#discussion_r1651153541
