### ISSUE TITLE
Add golangci-lint to project

### ISSUE THREAD

**Issue by ccoVeille** [supitsdu/clipper#20]
I can help you to add golangci-lint to your project. 

Many of the issues I raised would have been detected.

Using golangci-lint helped me a lot in my understanding of Go

**Comment by supitsdu** [comment]
Good decision, I was missing something while working on this project and sure thing was a linter.

**Comment by ccoVeille** [comment]
Sure then I will @ccoVeille, could you assign me the ticket ?

Thanks

**Comment by ccoVeille** [comment]
You inspired me to create

https://github.com/ccoVeille/golangci-lint-config-examples

It's empty now, but you can star and watch
